// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PotteryAlbum",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Pottery Album",
            targets: ["AppModule"],
            bundleIdentifier: "com.jkwok.potteryalbum",
            teamIdentifier: "5SQZ53CYMT",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "Save and manage pottery photos"),
                .camera(purposeString: "Take photos of your pottery pieces")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "App",
            resources: [
                .process("Assets.xcassets")
            ]
        ),
        .testTarget(
            name: "AppModuleTests",
            dependencies: ["AppModule"],
            path: "Tests"
        )
    ]
)